#AUTO CONFIGURE APACHE SERVER ON TARGET MACHINE AND HOSTS YOUR WEBSITE..
# COPY your website in /myweb folder and run the script from outside this folder
#
# (OPTIONAL) Go to /etc/ansible/hosts   and enter the IP address of the systems in which you want automation.. 
#
# In case of multiple systems / IPs ...  assign them group name as -->
# [a]
# IP1...
# IP2...
# IP3..

---
 - hosts: a  # you can enter either group name or single IP..
   remote_user: ec2-user
   sudo: yes
   tasks:
     - name:  Installing Apache HTTP server..
       yum:
        name: httpd
        state: latest

     - name: Copying Website ...
       copy:
        src: ./myweb/
        dest: /var/www/html

     - name: Starting Apache Server
       service:
        name: httpd
        state: started
        enabled: yes
